version: '3'

services:
  db:
    image: mysql:5.7
    container_name: sb_db
    environment:
      MYSQL_ROOT_PASSWORD: ultra-safe-password
      MYSQL_DATABASE: sharebucket_db
      MYSQL_USER: sharebucket_admin
      MYSQL_PASSWORD: sharebucket_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d

  web:
    build: ./php/
    container_name: sb_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8080:80"
      
  adminer:
    image: adminer
    ports:
      - 8000:8080