version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: sharebucket_db
      MYSQL_USER: sharebucket_admin
      MYSQL_PASSWORD: sharebucket_password
    ports:
      - "3306:3306"

  web:
    build: ./php/
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8080:80"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8000:80
    depends_on: 
      - db
    environment:
        MYSQL_USER: sharebucket_admin
        MYSQL_PASSWORD: sharebucket_password
        PMA_PORT: "3306"
        PMA_USER: sharebucket_admin
        PAM_PASSWORD: sharebucket_password
        PMA_HOST: db