-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 11:11:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sharebucket_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sharebucket_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sharebucket_db` DEFAULT CHARACTER SET utf8 ;
USE `sharebucket_db` ;

-- -----------------------------------------------------
-- Table `sharebucket_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebucket_db`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebucket_db`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebucket_db`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(50) NOT NULL,
  `color` CHAR(7) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharebucket_db`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharebucket_db`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idCategory` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `short_description` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `public` TINYINT(1) NOT NULL,
  `created` DATE NOT NULL,
  PRIMARY KEY (`idProject`),
  INDEX `fk_Project_User_idx` (`idUser` ASC),
  INDEX `fk_Project_Category1_idx` (`idCategory` ASC),
  CONSTRAINT `fk_Project_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `sharebucket_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `sharebucket_db`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Category ( topic, color) VALUES ( "Webentwicklung", "#007BFF");
INSERT INTO Category ( topic, color) VALUES ( "Machine Learning", "#A000FF");
INSERT INTO Category ( topic, color) VALUES ( "Kryptographie", "#BA0500");
INSERT INTO Category ( topic, color) VALUES ( "Sonstiges", "#FF5600");